SET TERM ^ ;

CREATE OR ALTER TRIGGER ATUALIZA_ESTOQUE FOR MOVIMENTODETALHE
ACTIVE AFTER UPDATE OR DELETE POSITION 0
AS 
DECLARE variable DTAMOV DATE;
DECLARE variable CCUSTO INTEGER;
DECLARE variable CODPROD INTEGER;
DECLARE variable BAIXAMOV smallint;
DECLARE variable PRECOCOMPRA double precision;
DECLARE variable PRECOCUSTO double precision;
DECLARE variable PRECOULTIMACOMPRA double precision;
DECLARE variable PRECOVENDA double precision;
DECLARE variable ESTOQUE double precision;
DECLARE variable LOTE VARCHAR(60);
BEGIN 
  IF (((deleting) and (old.BAIXA is not null)) OR ((updating) and (new.BAIXA is not null))) then
  begin  
	/* RODA O ATUALIZA ESTOQUE */
	SELECT M.DATAMOVIMENTO, M.CODALMOXARIFADO, NOP.BAIXAMOVIMENTO 
	  FROM MOVIMENTO M, NATUREZAOPERACAO NOP 
     WHERE M.CODNATUREZA = NOP.CODNATUREZA
       AND CODMOVIMENTO = OLD.CODMOVIMENTO 
     into :DTAMOV, :CCUSTO, :BAIXAMOV;
	FOR SELECT  ev.PRECOCOMPRA, ev.PRECOCUSTO, ev.PRECOUNIT, ev.PRECOVENDA, ev.SALDOFIMACUM 
	      FROM ESTOQUE_VIEW(:DTAMOV, OLD.CODPRODUTO, :CCUSTO, 'TODOS OS LOTES CADASTRADOS NO SISTEMA') ev
          INTO :PRECOCOMPRA, :PRECOCUSTO, :PRECOULTIMACOMPRA, :PRECOVENDA, :ESTOQUE
    DO BEGIN
      SELECT FIRST 1 EM.CODPRODUTO, em.PRECOCOMPRA FROM ESTOQUEMES EM 
       WHERE EM.CODPRODUTO = OLD.CODPRODUTO
         AND EM.MESANO = '01/01/2001'
         AND EM.CENTROCUSTO = :CCUSTO
          --AND EM.LOTE   = OLD.LOTE
        INTO :CODPROD, :PRECOULTIMACOMPRA;
        IF (CODPROD IS NULL) THEN 
          CODPROD = 0;  
          
        --select ev. from ESTOQUE_VIEW('01/01/2001', :OLD.CODPRODUTO, :CCUSTO, 'TODOS OS LOTES CADASTRADOS NO SISTEMA') ev   
        lote = old.LOTE;
        if (old.lote is null) then 
          lote = '0';
        
          
        IF (CODPROD = 0) THEN 
        BEGIN 
          IF (:BAIXAMOV = 0) THEN  
          INSERT INTO ESTOQUEMES (CODPRODUTO, LOTE, MESANO, CENTROCUSTO, PRECOCUSTO, PRECOCOMPRA, PRECOCOMPRAULTIMA, PRECOVENDA, SALDOMESANTERIOR, 
             QTDEENTRADA, QTDECOMPRA, QTDEDEVCOMPRA, QTDESAIDA, QTDEVENDA, QTDEPERDA, QTDEDEVVENDA, QTDEINVENTARIO)
            VALUES (OLD.CODPRODUTO, :LOTE, '01/01/2001', :CCUSTO, :PRECOCUSTO, :PRECOCOMPRA, :PRECOULTIMACOMPRA, :PRECOVENDA, :ESTOQUE, 
              0,           0,         0,             0,         0,         0,         0,            0);
        END 
        IF (CODPROD > 0) THEN 
        BEGIN 
          UPDATE ESTOQUEMES SET PRECOCUSTO = :PRECOCUSTO, PRECOCOMPRA = :PRECOCOMPRA, PRECOCOMPRAULTIMA = :PRECOULTIMACOMPRA, PRECOVENDA = :PRECOVENDA,
            SALDOMESANTERIOR = :ESTOQUE 
           WHERE CODPRODUTO = OLD.CODPRODUTO 
             AND MESANO = '01/01/2001'
             AND CENTROCUSTO = :CCUSTO
             AND LOTE = :LOTE;
             
        END 
        CODPROD = NULL;     
        
    END
  end -- if inicial     
END^

SET TERM ; ^ 
