CREATE OR ALTER PROCEDURE SP_CONTAS_PENDENTES (
    DTAINI DATE,
    DTAFIM DATE)
RETURNS (
    DTAEMISSAO DATE,
    DTAPAGTO DATE,
    CODFORN INTEGER,
    FORNECEDOR VARCHAR(60),
    DESCRICAO VARCHAR(150),
    VALORTIT DOUBLE PRECISION,
    VALORPAGO DOUBLE PRECISION,
    CONTACONTABIL VARCHAR(60),
    CAIXA VARCHAR(60),
    CODCONTA VARCHAR(15))
AS
DECLARE VARIABLE CCAIXA INTEGER;
DECLARE VARIABLE CCONTABIL INTEGER;
BEGIN



  /* Lista os pagamentos efetuados */ 


  FOR SELECT pag.EMISSAO, pag.DATAPAGAMENTO, CAST(pag.CODFORNECEDOR AS VARCHAR(5)) || '-' ||  forn.NOMEFORNECEDOR, 
    pag.HISTORICO, pag.VALORTITULO, pag.VALORRECEBIDO, pag.CONTACREDITO,pag.CAIXA  
    FROM PAGAMENTO pag, FORNECEDOR forn where forn.CODFORNECEDOR = pag.CODFORNECEDOR 
    and pag.EMISSAO BETWEEN :DTAINI AND :DTAFIM
  INTO :DTAEMISSAO, :DTAPAGTO, :FORNECEDOR, :DESCRICAO, :VALORTIT, :VALORPAGO, :CCONTABIL, :CCAIXA 
  DO BEGIN

    SELECT NOME, CODREDUZIDO FROM PLANO WHERE CODIGO = :CCONTABIL
    INTO :CONTACONTABIL, :CODCONTA;
    CONTACONTABIL = CODCONTA || '-' || CONTACONTABIL;
    SELECT NOME FROM PLANO WHERE CODIGO = :CCAIXA
    INTO :CAIXA;



    SUSPEND;
  END
END 





