CREATE OR ALTER TRIGGER BLOQ_CLI FOR RECEBIMENTO ACTIVE 
AFTER UPDATE POSITION 0
AS
  DECLARE VARIABLE VLR_RESTO DOUBLE PRECISION;
  DECLARE VARIABLE CODCLI    INTEGER;  
begin
    
    -- Verifica se há contas a pagar
    SELECT sum(r.VALOR_RESTO) as VALOR_RESTO, r.CODCLIENTE
    FROM RECEBIMENTO r WHERE (DATAVENCIMENTO < CURRENT_DATE) AND (CODCLIENTE = 9)
    AND ((STATUS = '5-') OR (STATUS = '6-'))
    GROUP BY r.CODCLIENTE
    INTO :VLR_RESTO, :CODCLI;
    
    -- Caso não aja desbloqueia cliente
    IF (NOT :VLR_RESTO > 0) THEN
        UPDATE CLIENTES SET BLOQUEIO = 'N' where CODCLIENTE = :CODCLI;
end