set term ^;

ALTER TABLE PRODUTOS
  ADD CONSTRAINT FK_PROD_CATEGORIA
        FOREIGN KEY ( CATEGORIA ) 
        REFERENCES CATEGORIAPRODUTO ( DESCCATEGORIA )
          ON UPDATE "CASCADE"
          ON DELETE "NO ACTION"
, ADD CONSTRAINT FK_PROD_FAMILIA
        FOREIGN KEY ( FAMILIA ) 
        REFERENCES FAMILIAPRODUTOS ( DESCFAMILIA )
          ON UPDATE "CASCADE"
          ON DELETE "NO ACTION"
, ADD CONSTRAINT FK_PROD_MARCA
        FOREIGN KEY ( MARCA ) 
        REFERENCES MARCA ( DESCMARCAS )
          ON UPDATE "CASCADE"
          ON DELETE "NO ACTION"
