set term ^;

ALTER TABLE PRODUTOS drop CONSTRAINT FK_PROD_CATEGORIA ^

commit ^

ALTER TABLE PRODUTOS DROP CONSTRAINT FK_PROD_FAMILIA ^

commit ^

ALTER TABLE PRODUTOS DROP CONSTRAINT FK_PROD_MARCA ^

commit ^
