set term  ^ ;
CREATE OR ALTER trigger gera_rec for recebimento
active after update position 0
AS
  DECLARE VARIABLE status_venda char(2);
  DECLARE VARIABLE VLR_RESTO DOUBLE PRECISION;
  DECLARE VARIABLE CODORIG INTEGER;  
begin
--  IF (OLD.CODORIGEM IS NULL) THEN 
    CODORIG =  OLD.CODRECEBIMENTO;
--  IF (OLD.CODORIGEM = 0) THEN 
    --CODORIG = NULL;
  
  IF ((OLD.STATUS <> '7-') and (NEW.STATUS = '7-') and (OLD.STATUS <> '1-')) THEN
    IF (((NEW.VALORRECEBIDO)+0.001) < OLD.VALOR_RESTO) THEN
    begin
     status_venda = '5-';
     VLR_RESTO =  ((OLD.VALOR_RESTO - NEW.DESCONTO - NEW.PERDA - NEW.TROCA)- NEW.VALORRECEBIDO) + NEW.JUROS;
     IF (VLR_RESTO > 0.009) then
     INSERT INTO RECEBIMENTO 
       (TITULO, EMISSAO, CODCLIENTE, DATAVENCIMENTO, STATUS , VIA, FORMARECEBIMENTO, 
       CODALMOXARIFADO, CODVENDEDOR, CODUSUARIO
       , DATASISTEMA, VALOR_PRIM_VIA, VALOR_RESTO, VALORTITULO, PARCELAS, CAIXA, 
       CODVENDA, CONTADEBITO, CONTACREDITO, PERDA, TROCA, FUNRURAL, CODORIGEM) 
     VALUES 
       (OLD.TITULO, OLD.EMISSAO, OLD.CODCLIENTE, OLD.DATAVENCIMENTO, 
       :status_venda, CAST((CAST(OLD.VIA as INTEGER) + 1) as CHAR(3)), OLD.FORMARECEBIMENTO, OLD.CODALMOXARIFADO, OLD.CODVENDEDOR, 
        OLD.CODUSUARIO,
       'NOW', 0, :VLR_RESTO, OLD.VALORTITULO, OLD.PARCELAS, OLD.CAIXA, OLD.CODVENDA, OLD.CONTADEBITO, 
       OLD.CONTACREDITO, 0,0,0, :CODORIG);
    --UPDATE RECEBIMENTO SET VALOR_RESTO = :VLR_RESTO WHERE CODRECEBIMENTO = OLD.CODRECEBIMENTO; 
   end
  IF ((OLD.STATUS <> '1-') and (NEW.STATUS = '1-')) THEN
    IF (((NEW.VALORRECEBIDO)+0.001) < OLD.VALOR_RESTO) THEN
    begin
     status_venda = '5-';
     VLR_RESTO =  ((OLD.VALOR_RESTO - NEW.DESCONTO - NEW.PERDA - NEW.TROCA)- NEW.VALORRECEBIDO) + NEW.JUROS;
     IF (VLR_RESTO > 0.009) then
     INSERT INTO RECEBIMENTO 
       (TITULO, EMISSAO, CODCLIENTE, DATAVENCIMENTO, STATUS , VIA, FORMARECEBIMENTO, 
       CODALMOXARIFADO, CODVENDEDOR, CODUSUARIO
       , DATASISTEMA, VALOR_PRIM_VIA, VALOR_RESTO, VALORTITULO, PARCELAS, CAIXA, 
       CODVENDA, CONTADEBITO, CONTACREDITO, PERDA, TROCA, FUNRURAL, CODORIGEM) 
     VALUES 
       (OLD.TITULO, OLD.EMISSAO, OLD.CODCLIENTE, OLD.DATAVENCIMENTO, 
       :status_venda, CAST((CAST(OLD.VIA as INTEGER) + 1) as CHAR(3)),OLD.FORMARECEBIMENTO, OLD.CODALMOXARIFADO, OLD.CODVENDEDOR, 
        OLD.CODUSUARIO,
       'NOW', 0, :VLR_RESTO, OLD.VALORTITULO, OLD.PARCELAS, OLD.CAIXA, OLD.CODVENDA, OLD.CONTADEBITO, 
       OLD.CONTACREDITO, 0,0,0, :CODORIG);
     --UPDATE RECEBIMENTO SET VALOR_RESTO = :VLR_RESTO WHERE CODRECEBIMENTO = OLD.CODRECEBIMENTO; 
   end

end
