CREATE OR ALTER TRIGGER INSERICLIFOR FOR FUNCIONARIO
ACTIVE BEFORE INSERT
POSITION 1
AS
BEGIN
   IF (new.clifor = 'S') THEN
   begin
      new.CODCLIENTE = gen_id(GEN_CLI, 1);
      new.CODFORNECEDOR = gen_id(GEN_FOR, 1);
      /* Inseri Cliente */
     Insert into CLIENTES (CODCLIENTE,NOMECLIENTE,RAZAOSOCIAL,TIPOFIRMA,SEGMENTO,
                 DATACADASTRO,STATUS,CODUSUARIO, REGIAO)
     Values(new.CODCLIENTE,new.NOME_FUNCIONARIO,new.NOME_FUNCIONARIO,0,1,'NOW',1,1,0);
     /* Inseri Fornecedor */
     Insert into FORNECEDOR(CODFORNECEDOR,NOMEFORNECEDOR,RAZAOSOCIAL,TIPOFIRMA,SEGMENTO,
                     DATACADASTRO,STATUS,CODUSUARIO, REGIAO)
     Values(new.CODFORNECEDOR,new.NOME_FUNCIONARIO,new.NOME_FUNCIONARIO,0,1,'NOW',1,1,0);
     
   end
  /* Trigger body */
END
;
