CREATE OR ALTER TRIGGER LOTE_exclui FOR MOVIMENTODETALHE ACTIVE
AFTER DELETE
POSITION 1
as
  DECLARE VARIABLE QTDEESTOQ DOUBLE PRECISION; 
  DECLARE VARIABLE TQTDEESTOQ DOUBLE PRECISION; 
  DECLARE VARIABLE ESTOQATUAL DOUBLE PRECISION; 
begin
 /* 1 = SAIDA */
 /* Acrescento a quantidade q foi retirada do estoque */
 if (OLD.BAIXA = '1') then
   IF (OLD.LOTE <> '') THEN
   BEGIN
     /* Procuro na tabela LOTES se já existe */
     SELECT ESTOQUE FROM LOTES WHERE LOTE = OLD.LOTE
     INTO :ESTOQATUAL;
     BEGIN
       IF (ESTOQATUAL IS NULL) THEN  
         ESTOQATUAL = 0;
       QTDEESTOQ = ESTOQATUAL + OLD.QUANTIDADE;
       UPDATE LOTES SET ESTOQUE = :QTDEESTOQ WHERE LOTE = OLD.LOTE;
     END
   end
 /* 0 = ENTRADA */
 /* Retiro do estoque o movimento deletado */
 if (OLD.BAIXA = '0') then
   IF (OLD.LOTE <> '') THEN
   BEGIN
     /* Procuro na tabela LOTES se já existe */
     SELECT ESTOQUE FROM LOTES WHERE LOTE = OLD.LOTE
     INTO :ESTOQATUAL;
     BEGIN
       IF (ESTOQATUAL IS NULL) THEN  
         ESTOQATUAL = 0;
       IF (OLD.QUANTIDADE < ESTOQATUAL) THEN
         TQTDEESTOQ = ESTOQATUAL - OLD.QUANTIDADE;
       IF (QTDEESTOQ <= OLD.QUANTIDADE) THEN
         TQTDEESTOQ = OLD.QUANTIDADE - ESTOQATUAL;
       UPDATE LOTES SET ESTOQUE = :TQTDEESTOQ WHERE LOTE = OLD.LOTE;
     END
   end

end