SET TERM ^ ;

CREATE TABLE ATUALIZA
( CODATUALIZA INTEGER NOT NULL PRIMARY KEY,
  SCRIPT VARCHAR(200),
  DATASCRIPT DATE,
  PARAQSERVE VARCHAR(200),
  VERSAO VARCHAR(50),
  INSERIDO CHAR(1)
)^

CREATE GENERATOR GEN_ATUALIZA^
SET GENERATOR GEN_ATUALIZA TO 0^

CREATE TRIGGER TRG_ATUALIZA FOR ATUALIZA ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODATUALIZA IS NULL) THEN
    NEW.CODATUALIZA = GEN_ID(GEN_ATUALIZA, 1); 
END^
