/******************************************************************************/
/****              Generated by IBExpert 26/03/2013 16:08:52               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE MOVDOCDET (
    CODOC       INTEGER NOT NULL,
    CODDETALHE  INTEGER,
    CODFIR      INTEGER,
    NOMERET     VARCHAR(60),
    NDOCRET     VARCHAR(100),
    DTPREV      DATE,
    DTRET       DATE,
    OBSRET      VARCHAR(60),
    OBS         BLOB SUB_TYPE 1 SEGMENT SIZE 4096,
    TIPO        CHAR(1),
    DTDEV       DATE,
    OBSDEV      BLOB SUB_TYPE 1 SEGMENT SIZE 4096,
    NOMEDEV     VARCHAR(60)
);




/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

