ALTER TRIGGER ENTRADA_ESTOQUE ACTIVE
AFTER UPDATE POSITION 0
as
  DECLARE VARIABLE QTDEESTOQ DOUBLE PRECISION; 
  DECLARE VARIABLE ESTOQATUAL DOUBLE PRECISION; 
begin
 SELECT ESTOQUEATUAL FROM PRODUTOS WHERE CODPRODUTO = OLD.CODPRODUTO
 INTO :ESTOQATUAL; 
 IF ((NEW.QUANTIDADE + ESTOQATUAL) > 0) THEN
 begin 
   QTDEESTOQ = NEW.QUANTIDADE + ESTOQATUAL;
 end 
 else
 begin
   QTDEESTOQ = 1;
 end 
 /* 0 = ENTRADA */
 if (NEW.BAIXA = '0') then
 begin
   update PRODUTOS set
       PRECOMEDIO = (((ESTOQUEATUAL * PRECOMEDIO) + (NEW.PRECO * NEW.QUANTIDADE))/:QTDEESTOQ),  
     ESTOQUEATUAL = ESTOQUEATUAL + NEW.QUANTIDADE,
     VALORUNITARIOANTERIOR = VALORUNITARIOATUAL,
     VALORUNITARIOATUAL = NEW.PRECO, 
     DATAULTIMACOMPRA = (SELECT DATAMOVIMENTO FROM MOVIMENTO WHERE CODMOVIMENTO = NEW.CODMOVIMENTO) 
   where CODPRODUTO = NEW.CODPRODUTO;
 end
end