SET TERM ^ ;

/* Altero as Trigger primeiro de COMPRA E VENDA, pois, estas não deixaão excluir */

/*create generator gen_cli_end^
*/
/*
SET GENERATOR GEN_COD_COMPRA TO 0^
SET GENERATOR COD_AREC TO 0^
SET GENERATOR GEN_COD_PAGAMENTO TO 0^
SET GENERATOR GEN_CONTAB_AUTOINC TO 0^
SET GENERATOR COD_MOV_RATEIO TO 0^
SET GENERATOR GEN_COD_CATEGORIA TO 0^
SET GENERATOR GEN_COD_FAMILIA TO 0^
SET GENERATOR GEN_PLANO_C TO 100^
SET GENERATOR GEN_CODIGOS TO 0^
SET GENERATOR GEN_PROD TO 0^
SET GENERATOR GEN_USO TO 0^
SET GENERATOR GEN_END_CLI TO 0^
SET GENERATOR GEN_CLI TO 0^
SET GENERATOR GEN_CLI_END TO 0^
SET GENERATOR GEN_COD_FUNC TO 0^
SET GENERATOR GEN_FOR TO 0^
SET GENERATOR GEN_FOR_END TO 0^
SET GENERATOR GEN_USER TO 0^  
*/
SET GENERATOR GEN_MOV_DET_SERV TO 0^
SET GENERATOR GEN_ITENS_NF TO 0^
SET GENERATOR GEN_CHEQ_BOL_DUPL TO 0^
SET GENERATOR GENMOVDET TO 0^
SET GENERATOR GENMOV TO 0^
SET GENERATOR GENVENDA TO 0^
SET GENERATOR GENORCAMENTO TO 0^
SET GENERATOR GEN_NF TO 0^
SET GENERATOR GEN_NF_SERV TO 0^

ALTER TRIGGER APAGA_ESTOQUE INACTIVE^


/*Zerando tabela informativo */
UPDATE INFORMATIVO SET 
  CODMOVIMENTO = 0,
  CODDETALHE = 0,
  CODVENDA = 0,
  CODRECEBIMENTO = 0,
  COD_CHEQ_BOL = 0^

/*ALTER TRIGGER APAGA_PAG INACTIVE^*/
/*ALTER TRIGGER APAGA_CONTABIL INACTIVE^*/
ALTER TRIGGER EXCLUI_PAG INACTIVE^
ALTER TRIGGER APAGA_REC INACTIVE^

commit ^

DELETE FROM CAIXAFECHAMENTO^
DELETE FROM ORCAMENTO^
DELETE FROM AGENDAMENTO^
DELETE FROM VENDA ^
DELETE FROM COMPRA ^
DELETE FROM notafiscal^

COMMIT^

DELETE FROM RECEBIMENTO^
DELETE FROM PAGAMENTO^
DELETE FROM MOVIMENTO^
DELETE FROM MOVIMENTOCONT^
DELETE FROM MOV_RATEIO^
DELETE FROM CHEQ_BOLETOS_DUPL^
DELETE FROM MOVIMENTONF^
DELETE FROM NOTAFISCAL_SERV^
DELETE FROM ORCAMENTO_TIPOS^
DELETE FROM ORCAMENTO^
DELETE FROM ESTOQUE^
DELETE FROM CHG^
DELETE FROM PROD_CHG^
DELETE FROM LISTAPRECO^

COMMIT^

/*Voltando as Trigger */
/* ALTER TRIGGER APAGA_PAG ACTIVE^*/
/*ALTER TRIGGER APAGA_CONTABIL ACTIVE^*/
ALTER TRIGGER EXCLUI_PAG ACTIVE^
ALTER TRIGGER APAGA_REC ACTIVE^
ALTER TRIGGER APAGA_ESTOQUE ACTIVE^
commit^

/* - - - - - - - - - - - - - - - -
List of possible problems detected
 - - - - - - - - - - - - - - - - -
None
- - - - - - - - - - - - - - - - */
SET TERM ; ^
