CREATE TABLE NOTAFISCAL_IMPORTA
(
    NOTAFISCAL INTEGER NOT NULL,
    NATUREZAOPERACAO VARCHAR(50),
    MODELO CHAR(5),
    SERIE  CHAR(5) not null ,
    EMISSAO DATE,
    CNPJ_EMITENTE VARCHAR(25) not null ,
    CNPJ_DESTINATARIO VARCHAR(25),
    NOME_EMITENTE VARCHAR(150),
    CODCLIENTE_ATS INTEGER,
    RAZAOSOCIAL_ATS VARCHAR(60),
    status SMALLINT default 0,
    PRIMARY KEY (NOTAFISCAL, SERIE, CNPJ_EMITENTE)
);
