/******************************************************************************/
/****              Generated by IBExpert 14/09/2022 16:42:26               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CTE_QC_ID;

CREATE TABLE CTE_QC (
    COD_CTE_QC  INTEGER NOT NULL,
    COD_CTE     INTEGER,
    UNID        VARCHAR(2),
    MEDIDA      VARCHAR(20),
    QUANT       DOUBLE PRECISION
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_QC ADD CONSTRAINT PK_CTE_QC_0 PRIMARY KEY (COD_CTE_QC);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_QC ADD CONSTRAINT FK_CTE_QC_0 FOREIGN KEY (COD_CTE) REFERENCES CTE (COD_CTE) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CTE_QC_BI */
CREATE OR ALTER TRIGGER CTE_QC_BI FOR CTE_QC
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.COD_CTE_QC IS NULL) THEN
    NEW.COD_CTE_QC = GEN_ID(GEN_CTE_QC_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CTE_QC_ID, 0);
    if (tmp < new.COD_CTE_QC) then
      tmp = GEN_ID(GEN_CTE_QC_ID, new.COD_CTE_QC-tmp);
  END
END
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

