/******************************************************************************/
/****              Generated by IBExpert 14/09/2022 16:40:01               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CTE_COMP_ID;

CREATE TABLE CTE_COMP (
    COD_CTE_COMP  INTEGER NOT NULL,
    COD_CTE       INTEGER,
    COMP_NOME     VARCHAR(15),
    COMP_VALOR    DOUBLE PRECISION
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_COMP ADD CONSTRAINT PK_CTE_COMP_0 PRIMARY KEY (COD_CTE_COMP);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_COMP ADD CONSTRAINT FK_CTE_COMP_CTE FOREIGN KEY (COD_CTE) REFERENCES CTE (COD_CTE) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CTE_COMP_BI */
CREATE OR ALTER TRIGGER CTE_COMP_BI FOR CTE_COMP
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.COD_CTE_COMP IS NULL) THEN
    NEW.COD_CTE_COMP = GEN_ID(GEN_CTE_COMP_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CTE_COMP_ID, 0);
    if (tmp < new.COD_CTE_COMP) then
      tmp = GEN_ID(GEN_CTE_COMP_ID, new.COD_CTE_COMP-tmp);
  END
END
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

