/******************************************************************************/
/****              Generated by IBExpert 14/09/2022 16:42:46               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CTE_SEGURO_ID;

CREATE TABLE CTE_SEGURO (
    COD_CTE_SEGURO    INTEGER NOT NULL,
    COD_CTE           INTEGER,
    RESP              INTEGER,
    NOME_SEGURADORA   VARCHAR(30),
    NUMERO_APOLICE    VARCHAR(20),
    VALOR             DOUBLE PRECISION,
    NUMERO_AVERBACAO  VARCHAR(20)
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_SEGURO ADD CONSTRAINT PK_CTE_SEGURO_0 PRIMARY KEY (COD_CTE_SEGURO);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_SEGURO ADD CONSTRAINT FK_CTE_SEGURO_0 FOREIGN KEY (COD_CTE) REFERENCES CTE (COD_CTE) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CTE_SEGURO_BI */
CREATE OR ALTER TRIGGER CTE_SEGURO_BI FOR CTE_SEGURO
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.COD_CTE_SEGURO IS NULL) THEN
    NEW.COD_CTE_SEGURO = GEN_ID(GEN_CTE_SEGURO_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CTE_SEGURO_ID, 0);
    if (tmp < new.COD_CTE_SEGURO) then
      tmp = GEN_ID(GEN_CTE_SEGURO_ID, new.COD_CTE_SEGURO-tmp);
  END
END
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

