/******************************************************************************/
/****              Generated by IBExpert 14/09/2022 16:43:06               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CTE_VEICULOS_ID;

CREATE TABLE CTE_VEICULOS (
    COD_CTE_VEICULOS  INTEGER NOT NULL,
    COD_CTE           INTEGER,
    CINT              VARCHAR(10),
    RENAVAM           VARCHAR(11),
    PLACA             VARCHAR(7),
    TARA              INTEGER,
    CAPKG             INTEGER,
    CAPM3             INTEGER,
    TPROD             VARCHAR(2),
    TPCAR             VARCHAR(2),
    TPVEIC            VARCHAR(1),
    TPPROP            VARCHAR(1),
    UF                VARCHAR(2),
    CNPJ              VARCHAR(20),
    RNTRC             VARCHAR(8),
    NOME              VARCHAR(60),
    IE                VARCHAR(20),
    VTPPROP           INTEGER,
    VUF               VARCHAR(2),
    VALINFCARGA       DOUBLE PRECISION
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_VEICULOS ADD CONSTRAINT PK_CTE_VEICULOS_0 PRIMARY KEY (COD_CTE_VEICULOS);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_VEICULOS ADD CONSTRAINT FK_CTE_VEICULOS_0 FOREIGN KEY (COD_CTE) REFERENCES CTE (COD_CTE) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CTE_VEICULOS_BI */
CREATE OR ALTER TRIGGER CTE_VEICULOS_BI FOR CTE_VEICULOS
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.COD_CTE_VEICULOS IS NULL) THEN
    NEW.COD_CTE_VEICULOS = GEN_ID(GEN_CTE_VEICULOS_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CTE_VEICULOS_ID, 0);
    if (tmp < new.COD_CTE_VEICULOS) then
      tmp = GEN_ID(GEN_CTE_VEICULOS_ID, new.COD_CTE_VEICULOS-tmp);
  END
END
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

