/******************************************************************************/
/****              Generated by IBExpert 14/09/2022 16:41:04               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CTE_MOTORISTA_ID;

CREATE TABLE CTE_MOTORISTA (
    COD_CTE_MOTORISTA  INTEGER NOT NULL,
    COD_CTE            INTEGER,
    CPF                VARCHAR(15),
    NOME               VARCHAR(60)
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_MOTORISTA ADD CONSTRAINT PK_CTE_MOTORISTA_0 PRIMARY KEY (COD_CTE_MOTORISTA);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_MOTORISTA ADD CONSTRAINT FK_CTE_MOTORISTA_CTE FOREIGN KEY (COD_CTE) REFERENCES CTE (COD_CTE) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CTE_MOTORISTA_BI */
CREATE OR ALTER TRIGGER CTE_MOTORISTA_BI FOR CTE_MOTORISTA
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.COD_CTE_MOTORISTA IS NULL) THEN
    NEW.COD_CTE_MOTORISTA = GEN_ID(GEN_CTE_MOTORISTA_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CTE_MOTORISTA_ID, 0);
    if (tmp < new.COD_CTE_MOTORISTA) then
      tmp = GEN_ID(GEN_CTE_MOTORISTA_ID, new.COD_CTE_MOTORISTA-tmp);
  END
END
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

