/******************************************************************************/
/****              Generated by IBExpert 14/09/2022 16:41:31               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CTE_NF_ID;

CREATE TABLE CTE_NF (
    COD_CTE_NF  INTEGER NOT NULL,
    COD_CTE     INTEGER,
    NFSERIE     VARCHAR(3),
    NFNUM       VARCHAR(20),
    NFEMI       DATE,
    NFCFOP      VARCHAR(4),
    NFMODELO    VARCHAR(2),
    NFROMA      VARCHAR(20),
    NFNUMP      VARCHAR(20),
    NFPREV      DATE,
    NFBASE      DOUBLE PRECISION,
    NFICMS      DOUBLE PRECISION,
    NFBASEST    DOUBLE PRECISION,
    NFICMSST    DOUBLE PRECISION,
    LNFPESO     DOUBLE PRECISION,
    NFPIN       INTEGER,
    NFVALPROD   DOUBLE PRECISION,
    NFVALOR     DOUBLE PRECISION
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_NF ADD CONSTRAINT PK_CTE_NF PRIMARY KEY (COD_CTE_NF);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CTE_NF ADD CONSTRAINT FK_CTE_NF_CTE FOREIGN KEY (COD_CTE) REFERENCES CTE (COD_CTE) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CTE_NF_BI */
CREATE OR ALTER TRIGGER CTE_NF_BI FOR CTE_NF
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.COD_CTE_NF IS NULL) THEN
    NEW.COD_CTE_NF = GEN_ID(GEN_CTE_NF_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CTE_NF_ID, 0);
    if (tmp < new.COD_CTE_NF) then
      tmp = GEN_ID(GEN_CTE_NF_ID, new.COD_CTE_NF-tmp);
  END
END
^


SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

