SET TERM ^ ;

CREATE TRIGGER ALTERA_STATUS FOR COMPRA
ACTIVE AFTER INSERT OR DELETE POSITION 1
AS 
  DECLARE VARIABLE CODPEDIDO INTEGER;
  DECLARE VARIABLE USA CHAR(10);
BEGIN 
	/* Altera o Status do Pedido para Finalizado ou volta para o Status Anterior */ 
    IF (INSERTING) THEN 
    begin
      UPDATE MOVIMENTO SET STATUS = 4 WHERE CODMOVIMENTO = NEW.CODMOVIMENTO;
      /*SELECT CODPEDIDO FROM MOVIMENTO WHERE CODMOVIMENTO = NEW.CODMOVIMENTO
      INTO :CODPEDIDO;
      
      SELECT CODMOVIMENTO FROM MOVIMENTO M 
       WHERE M.CONTROLE = :CODPEDIDO 
         AND M.CODNATUREZA = 5
      INTO :CODPEDIDO;
      
      UPDATE MOVIMENTO SET STATUS = 4 WHERE CODPEDIDO = ş*/
    end 
    IF (DELETING) THEN 
    begin
      SELECT CONFIGURADO FROM PARAMETRO WHERE PARAMETRO = 'COMPRA'
      INTO USA;
      IF (USA IS NULL) THEN 
        USA = 'N';
        
      IF (USA = 'S') THEN 
      BEGIN 
        UPDATE MOVIMENTO SET STATUS = 3 WHERE CODMOVIMENTO = old.CODMOVIMENTO;
      END   
      
      IF (USA = 'N') THEN 
      BEGIN 
        UPDATE MOVIMENTO SET STATUS = 0 WHERE CODMOVIMENTO = old.CODMOVIMENTO;
      END   
      
    end     
    
END^

SET TERM ; ^ 
