ALTER TRIGGER EXCLUI_PAG
AFTER DELETE
POSITION 0
AS
begin
/* Se o STATUS da Tab RECEBIMENTO for diferente de '5-', não é permitido fazer alteração */
  IF (EXISTS(SELECT STATUS FROM PAGAMENTO WHERE CODCOMPRA = OLD.CODCOMPRA)) THEN
  IF (NOT EXISTS(SELECT STATUS FROM PAGAMENTO WHERE CODCOMPRA = OLD.CODCOMPRA AND STATUS like '5-')) THEN
      EXCEPTION altera_venda_n_permitido;
   update PAGAMENTO set DP = 5 WHERE CODCOMPRA = OLD.CODCOMPRA;
   DELETE FROM PAGAMENTO WHERE CODCOMPRA = OLD.CODCOMPRA;
end