set term ^;

INSERT INTO PERMISSAO(CHAVE, TABELA, LOGIN, INCLUIR , EXCLUIR, ALTERAR, CONSULTAR) VALUES (
'adm-CLI','CLI','adm','S','S','S','S')^

INSERT INTO PERMISSAO(CHAVE, TABELA, LOGIN, INCLUIR , EXCLUIR, ALTERAR, CONSULTAR) VALUES (
'adm-FORN','FORN','adm','','','','')^
INSERT INTO PERMISSAO(CHAVE, TABELA, LOGIN, INCLUIR , EXCLUIR, ALTERAR, CONSULTAR) VALUES (
'adm-PROD','PROD','adm','S','S','S','S')^
INSERT INTO PERMISSAO(CHAVE, TABELA, LOGIN, INCLUIR , EXCLUIR, ALTERAR, CONSULTAR) VALUES (
'adm-COMP','COMP','adm','','','','')^
INSERT INTO PERMISSAO(CHAVE, TABELA, LOGIN, INCLUIR , EXCLUIR, ALTERAR, CONSULTAR) VALUES (
'adm-VEND','VEND','adm','S','S','S','S')^

