CREATE TABLE OF_OF
(
  OFID INTEGER NOT NULL,
  OFID_IND VARCHAR(20) CHARACTER SET NONE NOT NULL,
  OFDATA DATE,
  OFSTATUS CHAR(1),
  OFQTDESOLIC DOUBLE PRECISION,
  OFQTDEPRODUZ DOUBLE PRECISION,
  OFQTDEPERDA DOUBLE PRECISION,
  OFMOTIVO VARCHAR(100),
  CODPRODUTO INTEGER,
  CONSTRAINT PK_OF_OF PRIMARY KEY (OFID,OFID_IND)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON OF_OF TO  SYSDBA WITH GRANT OPTION;

