CREATE OR ALTER PROCEDURE SP_CONTAS_REC_GERAIS (
    DTAINI Date,
    DTAFIM Date,
    CCUSTO INTEGER )
RETURNS (
    DTAEMISSAO Date,
    DTAVENC Date,
    CODCLI Integer,
    CLIENTES Varchar(60),
    DESCRICAO Varchar(150),
    VALORTITULO Double precision,
    VALORPAGO Double precision,
    CONTACONTABIL Varchar(100),
    CAIXA Varchar(60),
    CODCONTA Varchar(15),
    N_TITULO VARCHAR(15) )
AS
DECLARE VARIABLE CCAIXA INTEGER;
DECLARE VARIABLE CCONTABIL INTEGER;
BEGIN



  /* Lista as contas a receber e recebidas gerais */


  FOR SELECT rec.EMISSAO ,rec.DATAVENCIMENTO, CAST(rec.CODCLIENTE AS VARCHAR(10)) || '-' ||  cli.NOMECLIENTE,
    rec.HISTORICO, rec.valor_prim_via, rec.VALORRECEBIDO, rec.CONTACREDITO,rec.CAIXA, rec.TITULO
    FROM RECEBIMENTO rec, CLIENTES cli where cli.CODCLIENTE = rec.CODCLIENTE
    and rec.EMISSAO BETWEEN :DTAINI AND :DTAFIM 
    and rec.valor_prim_via > 0 
    AND ((rec.CODALMOXARIFADO = :CCUSTO) or (:CCUSTO = 0))
    order by rec.EMISSAO
  INTO :DTAEMISSAO, :DTAVENC, :CLIENTES, :DESCRICAO, :VALORTITULO, :VALORPAGO, :CCONTABIL, :CCAIXA, :N_TITULO
  DO BEGIN

    SELECT NOME, CODREDUZIDO FROM PLANO WHERE CODIGO = :CCONTABIL
    INTO :CONTACONTABIL, :CODCONTA;
    CONTACONTABIL = CODCONTA || '-' || CONTACONTABIL;
    SELECT NOME FROM PLANO WHERE CODIGO = :CCAIXA
    INTO :CAIXA;


    SUSPEND;
    contacontabil = null;
  END
END

