CREATE OR ALTER PROCEDURE SP_CONTAS_A_RECEBER (
    DTAINI Date,
    DTAFIM Date,
    CCUSTO INTEGER )
RETURNS (
    DTAEMISSAO Date,
    DTAVENC Date,
    CODFORN Integer,
    CLIENTES Varchar(60),
    DESCRICAO Varchar(150),
    VALORRESTO Double precision,
    VALORPAGO Double precision,
    CONTACONTABIL Varchar(100),
    CAIXA Varchar(60),
    CODCONTA Varchar(15),
    STATUS Varchar(30),
    N_TITULO VARCHAR(15) )
AS
DECLARE VARIABLE CCAIXA INTEGER;
DECLARE VARIABLE CCONTABIL INTEGER;
BEGIN

  /* Lista as contas a receber */

  FOR SELECT rec.EMISSAO ,rec.DATAVENCIMENTO, CAST(rec.CODCLIENTE AS VARCHAR(10)) || '-' ||  cli.NOMECLIENTE,
    rec.HISTORICO, rec.VALOR_RESTO, rec.VALORRECEBIDO, rec.CONTACREDITO,rec.CAIXA, rec.STATUS, rec.TITULO
    FROM RECEBIMENTO rec, CLIENTES cli where cli.CODCLIENTE = rec.CODCLIENTE
    and ((rec.status = '5-') or (rec.status = '1-')) 
    and rec.DATAVENCIMENTO BETWEEN :DTAINI AND :DTAFIM 
    AND ((rec.CODALMOXARIFADO = :CCUSTO) or (:CCUSTO = 0))
    order by rec.DATAVENCIMENTO
  INTO :DTAEMISSAO, :DTAVENC, :CLIENTES, :DESCRICAO, :VALORRESTO, :VALORPAGO, :CCONTABIL, :CCAIXA, :STATUS, :N_TITULO
  DO BEGIN

    SELECT NOME, CODREDUZIDO FROM PLANO WHERE CODIGO = :CCONTABIL
    INTO :CONTACONTABIL, :CODCONTA;
    CONTACONTABIL = CODCONTA || '-' || CONTACONTABIL;
    SELECT NOME FROM PLANO WHERE CODIGO = :CCAIXA
    INTO :CAIXA;
    
    IF (STATUS = '1-') THEN
      STATUS = 'Cheque-Pré';

    IF (STATUS = '5-') THEN
      STATUS = 'Pendente';
   

    SUSPEND;
    contacontabil = null;
  END
END

