SET TERM ^ ;
ALTER PROCEDURE SP_DESPESAS_PAGAR (
    DTAINI DATE,
    DTAFIM DATE,
    COD_FOR INTEGER,
    COD_CCUSTO SMALLINT,
    COD_CONTA INTEGER,
    COD_CAIXA SMALLINT )
RETURNS (
    DTAEMISSAO DATE,
    DTAVENC DATE,
    CODFORN INTEGER,
    FORNECEDOR VARCHAR(60),
    DESCRICAO VARCHAR(150),
    VALORTITULO DOUBLE PRECISION,
    VALORPAGO DOUBLE PRECISION,
    CONTACONTABIL VARCHAR(200),
    CAIXA VARCHAR(60),
    CODCONTA VARCHAR(15),
    TITULO VARCHAR(30) )
AS
DECLARE VARIABLE CCAIXA INTEGER;
DECLARE VARIABLE N_TITULO VARCHAR(15);
DECLARE VARIABLE CCONTABIL INTEGER;
BEGIN



  /* Lista as contas efetuados */


  FOR SELECT pag.EMISSAO ,pag.DATAVENCIMENTO, pag.CODFORNECEDOR, forn.NOMEFORNECEDOR, 
    pag.HISTORICO, sum(pag.valor_RESTO), sum(pag.VALORRECEBIDO), pag.CONTACREDITO,pag.CAIXA, pag.TITULO
    FROM PAGAMENTO pag, FORNECEDOR forn where pag.CODCOMPRA is null
    and pag.EMISSAO BETWEEN :DTAINI AND :DTAFIM 
    and (forn.CODFORNECEDOR = pag.CODFORNECEDOR)
    and ((pag.CODFORNECEDOR = :cod_for) or (:cod_for = 9999999))
    and ((pag.CODALMOXARIFADO = :COD_CCUSTO) or (:COD_CCUSTO = 0))
    and ((pag.CONTACREDITO = :COD_CONTA) or (:COD_CONTA = 9999999))
    and ((pag.CAIXA = :COD_CAIXA) or (:COD_CAIXA = 0))
     group by pag.EMISSAO ,pag.DATAVENCIMENTO, pag.CODFORNECEDOR, forn.NOMEFORNECEDOR, 
     pag.HISTORICO, pag.CONTACREDITO,pag.CAIXA, pag.TITULO
    order by pag.EMISSAO
  INTO :DTAEMISSAO, :DTAVENC, :CODFORN, :FORNECEDOR, :DESCRICAO, :VALORTITULO, :VALORPAGO, :CCONTABIL, :CCAIXA, :TITULO
  DO BEGIN
    FORNECEDOR = CAST(:CODFORN AS VARCHAR(5)) || '-' ||  :FORNECEDOR;
    SELECT NOME, CODREDUZIDO FROM PLANO WHERE CODIGO = :CCONTABIL
    INTO :CONTACONTABIL, :CODCONTA;
    CONTACONTABIL = CODCONTA || '-' || CONTACONTABIL;
    SELECT NOME FROM PLANO WHERE CODIGO = :CCAIXA
    INTO :CAIXA;

    SUSPEND;
    descricao = null;
    ccontabil = null;
    caixa = null;
  END
END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE SP_DESPESAS_PAGAR TO  SYSDBA;

