CREATE TABLE mdfe
(
    cod_mdfe INTEGER not null ,
    codEmitente integer not null, 
    tipoEmitente SMALLINT,
    modelo SMALLINT,
    serie SMALLINT,
    numero_mdf INTEGER,
    chave_mdf integer,
    digito_mdf SMALLINT,
    modalidade SMALLINT,
    data_mdf TIMESTAMP,
    forma_emissao SMALLINT,
    versao_aplicativo varchar(20),
    uf_carregamento CHAR(2),
    uf_descarregamento CHAR(2),
    cod_municipio_carreg varchar(10),
    municipo_carreg varchar(60),
    uf_percurso char(2),
    cod_municipio_descarreg INTEGER,
    municipo_descarreg varchar(60),
    chave_nfe1 varchar(80),
    chave_nfe2 varchar(80),
    chave_nfe3 varchar(80),
    chave_nfe4 varchar(80),
    chave_nfe5 varchar(80),
    chave_nfe6 varchar(80),
    chave_nfe7 varchar(80),
    tipo_transp SMALLINT,
    unid_transp VARCHAR(20),
    tipo_carga SMALLINT,
    unid_carga varchar(20),
    ident_carga varchar(20),
    qtde_nfe SMALLINT,
    valor_carga double precision,
    unid_peso smallint,
    peso_bruto double precision,
    cnpj_autorizado1 varchar(20),
    cnpj_autorizado2 varchar(20),
    info_adic_fisco varchar(600),
    info_adic_contribuinte varchar(600),
    rntrc varchar(10), 
    ciot varchar(15),
    cint varchar(10),
    placa varchar(10),
    tara integer,
    capKg integer,
    capM3 integer,
    prop_cnpj varchar(20),
    prop_rntrc varchar(10),
    prop_nome varchar(60),
    prop_ie varchar(24),
    prop_uf char(2),
    prop_tipo SMALLINT,
    condutor_nome varchar(60),
    condutor_cpf varchar(14),
    tipo_rodado smallint,
    tipo_carroceria smallint,
    uf_veiculo char(2),
    reboque_cint varchar(10),
    reboque_placa varchar(10),
    reboque_tara integer,
    reboque_capkg integer,
    reboque_capm3 integer,
    reboque_cpf varchar(14),
    reboque_cnpj varchar(20),
    reboque_rntrc varchar(10),
    reboque_nome varchar(60),
    reboque_ie varchar(20),
    reboque_uf char(2),
    reboque_tipoprop smallint,
    reboque_tipocarroceria smallint,
    reboque_ufveiculo char(2),
    peso_volume1 double PRECISION,
    peso_volume2 double PRECISION,
    peso_volume3 double PRECISION,
    peso_volume4 double PRECISION,
    peso_volume5 double PRECISION,
    peso_volume6 double PRECISION,
    peso_volume7 double PRECISION,
    chave_mdfe varchar(80),
    PRIMARY KEY (cod_mdfe)
);
