-- drop PROCEDURE INVENTARIO_LANCA;

drop table inventario; 

/*
CREATE TABLE INVENTARIO
(
  CODIVENTARIO Varchar(40) NOT NULL,
  DATAIVENTARIO Date,
  CODPRODUTO Integer,
  CODPRO Varchar(15),
  SITUACAO Char(1),
  DATAEXECUTADO Date,
  ESTOQUE_ATUAL VALOR DEFAULT 0,
  QTDE_INVENTARIO VALOR DEFAULT 0,
  UN TEXTO3,
  PRIMARY KEY (CODIVENTARIO, CODPRODUTO)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INVENTARIO TO  SYSDBA WITH GRANT OPTION;

*/