SET TERM ^ ;

CREATE OR ALTER PROCEDURE mdfe_duplica 
 ( num_mdfe integer ) 
AS 
DECLARE VARIABLE COD INTEGER;
BEGIN
  SELECT MAX(COD_MDFE) COD FROM MDFE 
    INTO :COD;
  COD = COD + 1;
  INSERT INTO MDFE (COD_MDFE, CODEMITENTE,
    TIPOEMITENTE, MODELO, SERIE, NUMERO_MDF,
    DIGITO_MDF, MODALIDADE, DATA_MDF, CHAVE_MDF,
    FORMA_EMISSAO, VERSAO_APLICATIVO, UF_CARREGAMENTO, UF_DESCARREGAMENTO,
    COD_MUNICIPIO_CARREG, MUNICIPO_CARREG, UF_PERCURSO, COD_MUNICIPIO_DESCARREG,
    MUNICIPO_DESCARREG, TIPO_TRANSP, UNID_TRANSP, TIPO_CARGA, 
    UNID_CARGA, IDENT_CARGA, QTDE_NFE, VALOR_CARGA, 
    UNID_PESO, PESO_BRUTO, CNPJ_AUTORIZADO1, CNPJ_AUTORIZADO2,
    INFO_ADIC_FISCO, INFO_ADIC_CONTRIBUINTE,  RNTRC, CIOT, 
    CINT, PLACA, TARA, CAPKG, 
    CAPM3, PROP_CNPJ, PROP_RNTRC, PROP_NOME,
    PROP_IE, PROP_UF, PROP_TIPO, CONDUTOR_NOME,
    CONDUTOR_CPF, TIPO_RODADO, TIPO_CARROCERIA, UF_VEICULO, 
    REBOQUE_CINT, REBOQUE_PLACA,  REBOQUE_TARA, REBOQUE_CAPKG, 
    REBOQUE_CAPM3, REBOQUE_CPF, REBOQUE_CNPJ, REBOQUE_RNTRC,
    REBOQUE_NOME, REBOQUE_IE, REBOQUE_UF, REBOQUE_TIPOPROP, 
    REBOQUE_TIPOCARROCERIA,  REBOQUE_UFVEICULO, UF_PERCURSO2, UF_PERCURSO3, 
    UF_PERCURSO4, UF_PERCURSO5,  UF_PERCURSO6, TIPO_EMITENTE, 
    SEG_RESP, SEG_CNPJ_EMITENTE, SEG_SEGURADORA,
    SEG_CNPJ_SEGURADORA, SEG_APOLICE, SEG_AVERBA,
    CNPJ_CONTRATANTE, PESO_VOLUME1,
	NOME_CONTRATANTE, VALOR_CONTRATO, IND_PAG, BANCO_COD, BANCO_AGENCIA
    ,BANCO_CNPJ, ID_ESTRANGEIRO, TPCARGA, XPROD, CEAN, NCM 
  SELECT :cod, a.CODEMITENTE, a.TIPOEMITENTE,
    a.MODELO, a.SERIE, :cod, a.DIGITO_MDF,
    a.MODALIDADE, a.DATA_MDF, :cod, a.FORMA_EMISSAO,
    a.VERSAO_APLICATIVO, a.UF_CARREGAMENTO,
    a.UF_DESCARREGAMENTO, a.COD_MUNICIPIO_CARREG,
    a.MUNICIPO_CARREG, a.UF_PERCURSO,
    a.COD_MUNICIPIO_DESCARREG,
    a.MUNICIPO_DESCARREG, a.TIPO_TRANSP,
    a.UNID_TRANSP, a.TIPO_CARGA, a.UNID_CARGA,
    a.IDENT_CARGA, 0, 0,
    a.UNID_PESO, 0, a.CNPJ_AUTORIZADO1,
    a.CNPJ_AUTORIZADO2, a.INFO_ADIC_FISCO,
    a.INFO_ADIC_CONTRIBUINTE, a.RNTRC, a.CIOT,
    a.CINT, a.PLACA, a.TARA, a.CAPKG, a.CAPM3,
    a.PROP_CNPJ, a.PROP_RNTRC, a.PROP_NOME,
    a.PROP_IE, a.PROP_UF, a.PROP_TIPO,
    a.CONDUTOR_NOME, a.CONDUTOR_CPF,
    a.TIPO_RODADO, a.TIPO_CARROCERIA,
    a.UF_VEICULO, a.REBOQUE_CINT, a.REBOQUE_PLACA,
    a.REBOQUE_TARA, a.REBOQUE_CAPKG,
    a.REBOQUE_CAPM3, a.REBOQUE_CPF,
    a.REBOQUE_CNPJ, a.REBOQUE_RNTRC,
    a.REBOQUE_NOME, a.REBOQUE_IE, a.REBOQUE_UF,
    a.REBOQUE_TIPOPROP, a.REBOQUE_TIPOCARROCERIA,
    a.REBOQUE_UFVEICULO, a.UF_PERCURSO2,
    a.UF_PERCURSO3, a.UF_PERCURSO4,
    a.UF_PERCURSO5, a.UF_PERCURSO6,
    a.TIPO_EMITENTE, a.SEG_RESP,
    a.SEG_CNPJ_EMITENTE, a.SEG_SEGURADORA,
    a.SEG_CNPJ_SEGURADORA, a.SEG_APOLICE,
    a.SEG_AVERBA, a.CNPJ_CONTRATANTE, 0,
	a.NOME_CONTRATANTE, a.VALOR_CONTRATO, a.IND_PAG, a.BANCO_COD, a.BANCO_AGENCIA
    ,a.BANCO_CNPJ, a.ID_ESTRANGEIRO, a.TPCARGA, a.XPROD, a.CEAN, a.NCM 
    FROM MDFE a 
    WHERE
       a.COD_MDFE = :NUM_MDFE;
END^

SET TERM ; ^
