unit uFichaMedica;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, uPai_new, Menus, XPMenu, DB, StdCtrls, Buttons, ExtCtrls,
  MMJPanel, FMTBcd, DBCtrls, Mask, ComCtrls, SqlExpr, Provider, DBClient;

type
  TfFichaMedica = class(TfPai_new)
    cdsFicha: TClientDataSet;
    cdsFichaID_FICHA: TIntegerField;
    cdsFichaRA: TStringField;
    cdsFichaD_MENTAL: TStringField;
    cdsFichaD_VISUAL: TStringField;
    cdsFichaD_AUDITIVA: TStringField;
    cdsFichaD_FISICA: TStringField;
    cdsFichaD_MULTIPLA: TStringField;
    cdsFichaSUPER_DOTADO: TStringField;
    cdsFichaCONDUTA_TIPICA: TStringField;
    cdsFichaOUTROS: TStringField;
    cdsFichaOUTROS_H: TMemoField;
    cdsFichaTEM_ACOMPANHANTE: TStringField;
    cdsFichaTIPO_ACOMPANHANTE: TStringField;
    cdsFichaCQUEMMORA: TStringField;
    cdsFichaNOME_OUTROS: TStringField;
    cdsFichaEMPRESA_OUTROS: TStringField;
    cdsFichaFONE_OUTROS: TStringField;
    cdsFichaFONE1_OUTROS: TStringField;
    cdsFichaFONE2_OUTROS: TStringField;
    cdsFichaRAMAL_OUTROS: TStringField;
    cdsFichaHORAS_ESTUDA: TIntegerField;
    cdsFichaPROFESSORES_PARTICULAR: TIntegerField;
    cdsFichaCANHOTO_DESTRO: TIntegerField;
    cdsFichaALERGICO: TStringField;
    cdsFichaTIPO_ALERGIA: TStringField;
    cdsFichaMEDICO_ALUNO: TIntegerField;
    cdsFichaTRATAMENTO_MEDICO: TIntegerField;
    cdsFichaTIPO_TRATAMENTO: TStringField;
    cdsFichaINGERINDO_MEDICACAO: TIntegerField;
    cdsFichaTIPO_MEDICACAO: TStringField;
    cdsFichaNOME_MEDICO: TStringField;
    cdsFichaFONE_MEDICO: TStringField;
    cdsFichaENDERECO_MEDICO: TStringField;
    cdsFichaPLANO_SAUDE: TIntegerField;
    cdsFichaQUAL_PLANO: TStringField;
    cdsFichaSER_MEDICADO_POR: TStringField;
    cdsFichaDOENCA_CONGENITA: TIntegerField;
    cdsFichaQUAL_DOENCA: TStringField;
    cdsFichaCONTRAIU_CAXUMBA: TStringField;
    cdsFichaCONTRAIU_SARAMPO: TStringField;
    cdsFichaCONTRAIU_RUBEOLA: TStringField;
    cdsFichaCONTRAIU_CATAPORA: TStringField;
    cdsFichaCONTRAIU_ESCARLATINA: TStringField;
    cdsFichaCONTRAIU_COQUELUCHE: TStringField;
    cdsFichaCONTRAIU_OUTRAS: TStringField;
    cdsFichaQUAIS_OUTRA: TStringField;
    cdsFichaNOME_AVISO: TStringField;
    cdsFichaENDERECO_AVISO: TStringField;
    cdsFichaPARENTESCO_AVISO: TStringField;
    cdsFichaFONE_AVISO: TStringField;
    cdsFichaHOSPITAL_AVISO: TStringField;
    cdsFichaTEM_HIPERTENCAO: TIntegerField;
    cdsFichaHIPERTENCAO: TStringField;
    cdsFichaE_EPILETICO: TIntegerField;
    cdsFichaEPILETICO: TStringField;
    cdsFichaE_HEMOFILICO: TIntegerField;
    cdsFichaHEMOFILICO: TStringField;
    cdsFichaE_DEFICIENTE_AUDITIVO: TIntegerField;
    cdsFichaDEFICIENTE_AUDITIVO: TStringField;
    cdsFichaE_DEFICIENTE_VISUAL: TIntegerField;
    cdsFichaDEFICIENTE_VISUAL: TStringField;
    cdsFichaE_DEFICIENTE_FISICO: TIntegerField;
    cdsFichaDEFICIENTE_FISICO: TStringField;
    cdsFichaE_DIABETICO: TIntegerField;
    cdsFichaDIABETICO: TStringField;
    cdsFichaUSA_INSULINA: TIntegerField;
    cdsFichaAUTORIZADO_DX_ESCOLA_SOZ: TIntegerField;
    cdsFichaOBSERVACOES: TMemoField;
    cdsFichaMOTIVO_MEDICAMENTO: TStringField;
    cdsFichaAPTO: TStringField;
    cdsFichaESPERAR_FORA_ESCOLA: TIntegerField;
    cdsFichaFONE_HOSPITAL: TStringField;
    cdsFichaNOME_RETIRA: TStringField;
    cdsFichaENDERECO_RETIRA: TStringField;
    cdsFichaPARENTESCO_RETIRA: TStringField;
    cdsFichaFONE_RETIRA: TStringField;
    cdsFichaPSICOLOGO: TStringField;
    cdsFichaFISIOTERAPIA: TStringField;
    cdsFichaMEDICO: TStringField;
    cdsFichaFONOAUDIOLOGO: TStringField;
    cdsFichaPSICOPEDAGOGO: TStringField;
    cdsFichaOUTRO_1: TStringField;
    cdsFichaNAO: TStringField;
    cdsFichaE_ASMATICO: TIntegerField;
    cdsFichaASMATICO: TStringField;
    dspFicha: TDataSetProvider;
    sdsFicha: TSQLDataSet;
    sdsFichaID_FICHA: TIntegerField;
    sdsFichaRA: TStringField;
    sdsFichaD_MENTAL: TStringField;
    sdsFichaD_VISUAL: TStringField;
    sdsFichaD_AUDITIVA: TStringField;
    sdsFichaD_FISICA: TStringField;
    sdsFichaD_MULTIPLA: TStringField;
    sdsFichaSUPER_DOTADO: TStringField;
    sdsFichaCONDUTA_TIPICA: TStringField;
    sdsFichaOUTROS: TStringField;
    sdsFichaOUTROS_H: TMemoField;
    sdsFichaTEM_ACOMPANHANTE: TStringField;
    sdsFichaTIPO_ACOMPANHANTE: TStringField;
    sdsFichaCQUEMMORA: TStringField;
    sdsFichaNOME_OUTROS: TStringField;
    sdsFichaEMPRESA_OUTROS: TStringField;
    sdsFichaFONE_OUTROS: TStringField;
    sdsFichaFONE1_OUTROS: TStringField;
    sdsFichaFONE2_OUTROS: TStringField;
    sdsFichaRAMAL_OUTROS: TStringField;
    sdsFichaHORAS_ESTUDA: TIntegerField;
    sdsFichaPROFESSORES_PARTICULAR: TIntegerField;
    sdsFichaCANHOTO_DESTRO: TIntegerField;
    sdsFichaALERGICO: TStringField;
    sdsFichaTIPO_ALERGIA: TStringField;
    sdsFichaMEDICO_ALUNO: TIntegerField;
    sdsFichaTRATAMENTO_MEDICO: TIntegerField;
    sdsFichaTIPO_TRATAMENTO: TStringField;
    sdsFichaINGERINDO_MEDICACAO: TIntegerField;
    sdsFichaTIPO_MEDICACAO: TStringField;
    sdsFichaNOME_MEDICO: TStringField;
    sdsFichaFONE_MEDICO: TStringField;
    sdsFichaENDERECO_MEDICO: TStringField;
    sdsFichaPLANO_SAUDE: TIntegerField;
    sdsFichaQUAL_PLANO: TStringField;
    sdsFichaSER_MEDICADO_POR: TStringField;
    sdsFichaDOENCA_CONGENITA: TIntegerField;
    sdsFichaQUAL_DOENCA: TStringField;
    sdsFichaCONTRAIU_CAXUMBA: TStringField;
    sdsFichaCONTRAIU_SARAMPO: TStringField;
    sdsFichaCONTRAIU_RUBEOLA: TStringField;
    sdsFichaCONTRAIU_CATAPORA: TStringField;
    sdsFichaCONTRAIU_ESCARLATINA: TStringField;
    sdsFichaCONTRAIU_COQUELUCHE: TStringField;
    sdsFichaCONTRAIU_OUTRAS: TStringField;
    sdsFichaQUAIS_OUTRA: TStringField;
    sdsFichaNOME_AVISO: TStringField;
    sdsFichaENDERECO_AVISO: TStringField;
    sdsFichaPARENTESCO_AVISO: TStringField;
    sdsFichaFONE_AVISO: TStringField;
    sdsFichaHOSPITAL_AVISO: TStringField;
    sdsFichaTEM_HIPERTENCAO: TIntegerField;
    sdsFichaHIPERTENCAO: TStringField;
    sdsFichaE_EPILETICO: TIntegerField;
    sdsFichaEPILETICO: TStringField;
    sdsFichaE_HEMOFILICO: TIntegerField;
    sdsFichaHEMOFILICO: TStringField;
    sdsFichaE_DEFICIENTE_AUDITIVO: TIntegerField;
    sdsFichaDEFICIENTE_AUDITIVO: TStringField;
    sdsFichaE_DEFICIENTE_VISUAL: TIntegerField;
    sdsFichaDEFICIENTE_VISUAL: TStringField;
    sdsFichaE_DEFICIENTE_FISICO: TIntegerField;
    sdsFichaDEFICIENTE_FISICO: TStringField;
    sdsFichaE_DIABETICO: TIntegerField;
    sdsFichaDIABETICO: TStringField;
    sdsFichaUSA_INSULINA: TIntegerField;
    sdsFichaAUTORIZADO_DX_ESCOLA_SOZ: TIntegerField;
    sdsFichaOBSERVACOES: TMemoField;
    sdsFichaMOTIVO_MEDICAMENTO: TStringField;
    sdsFichaAPTO: TStringField;
    sdsFichaESPERAR_FORA_ESCOLA: TIntegerField;
    sdsFichaFONE_HOSPITAL: TStringField;
    sdsFichaNOME_RETIRA: TStringField;
    sdsFichaENDERECO_RETIRA: TStringField;
    sdsFichaPARENTESCO_RETIRA: TStringField;
    sdsFichaFONE_RETIRA: TStringField;
    sdsFichaPSICOLOGO: TStringField;
    sdsFichaFISIOTERAPIA: TStringField;
    sdsFichaMEDICO: TStringField;
    sdsFichaFONOAUDIOLOGO: TStringField;
    sdsFichaPSICOPEDAGOGO: TStringField;
    sdsFichaOUTRO_1: TStringField;
    sdsFichaNAO: TStringField;
    sdsFichaE_ASMATICO: TIntegerField;
    sdsFichaASMATICO: TStringField;
    PagAluno: TPageControl;
    TabDadosAdicionais: TTabSheet;
    Label89: TLabel;
    Label90: TLabel;
    Label91: TLabel;
    Label92: TLabel;
    Label93: TLabel;
    Label94: TLabel;
    Label95: TLabel;
    DBComboBox5: TDBComboBox;
    DBEdit65: TDBEdit;
    DBEdit66: TDBEdit;
    DBEdit67: TDBEdit;
    DBEdit68: TDBEdit;
    DBEdit69: TDBEdit;
    DBEdit70: TDBEdit;
    GroupBox15: TGroupBox;
    Label105: TLabel;
    Label106: TLabel;
    Label107: TLabel;
    Label108: TLabel;
    Label109: TLabel;
    DBEdit81: TDBEdit;
    DBEdit82: TDBEdit;
    DBEdit83: TDBEdit;
    DBEdit84: TDBEdit;
    DBEdit85: TDBEdit;
    DBRadioGroup20: TDBRadioGroup;
    DBRadioGroup21: TDBRadioGroup;
    DBRadioGroup19: TDBRadioGroup;
    DBRadioGroup18: TDBRadioGroup;
    GroupBox25: TGroupBox;
    Label110: TLabel;
    Label111: TLabel;
    Label113: TLabel;
    Label114: TLabel;
    DBEdit94: TDBEdit;
    DBEdit95: TDBEdit;
    DBEdit97: TDBEdit;
    DBEdit98: TDBEdit;
    TabFicha1: TTabSheet;
    Label99: TLabel;
    Label100: TLabel;
    Label101: TLabel;
    GroupBox5: TGroupBox;
    DBRadioGroup3: TDBRadioGroup;
    GroupBox8: TGroupBox;
    Label97: TLabel;
    DBRadioGroup4: TDBRadioGroup;
    DBEdit71: TDBEdit;
    DBRadioGroup5: TDBRadioGroup;
    GroupBox9: TGroupBox;
    Label96: TLabel;
    DBRadioGroup6: TDBRadioGroup;
    DBEdit72: TDBEdit;
    GroupBox10: TGroupBox;
    Label98: TLabel;
    DBRadioGroup7: TDBRadioGroup;
    DBEdit73: TDBEdit;
    DBEdit74: TDBEdit;
    DBEdit75: TDBEdit;
    DBEdit76: TDBEdit;
    TabFicha2: TTabSheet;
    GroupBox11: TGroupBox;
    Label102: TLabel;
    DBRadioGroup8: TDBRadioGroup;
    DBEdit77: TDBEdit;
    GroupBox12: TGroupBox;
    Label103: TLabel;
    DBRadioGroup9: TDBRadioGroup;
    DBEdit78: TDBEdit;
    GroupBox13: TGroupBox;
    DBEdit79: TDBEdit;
    GroupBox14: TGroupBox;
    Label104: TLabel;
    DBEdit80: TDBEdit;
    GroupBox6: TGroupBox;
    DBRadioGroup10: TDBRadioGroup;
    GroupBox16: TGroupBox;
    DBEdit86: TDBEdit;
    GroupBox17: TGroupBox;
    DBEdit87: TDBEdit;
    DBRadioGroup11: TDBRadioGroup;
    GroupBox18: TGroupBox;
    DBEdit88: TDBEdit;
    DBRadioGroup12: TDBRadioGroup;
    GroupBox19: TGroupBox;
    DBEdit89: TDBEdit;
    DBRadioGroup13: TDBRadioGroup;
    GroupBox20: TGroupBox;
    DBEdit90: TDBEdit;
    DBRadioGroup14: TDBRadioGroup;
    GroupBox21: TGroupBox;
    DBEdit91: TDBEdit;
    DBRadioGroup15: TDBRadioGroup;
    DBRadioGroup16: TDBRadioGroup;
    GroupBox22: TGroupBox;
    DBEdit92: TDBEdit;
    DBRadioGroup17: TDBRadioGroup;
    GroupBox23: TGroupBox;
    DBEdit93: TDBEdit;
    Label4: TLabel;
    Label3: TLabel;
    GroupBox1: TGroupBox;
    DBRadioGroup1: TDBRadioGroup;
    DBRadioGroup2: TDBRadioGroup;
    DBRadioGroup22: TDBRadioGroup;
    DBRadioGroup23: TDBRadioGroup;
    DBRadioGroup24: TDBRadioGroup;
    DBRadioGroup25: TDBRadioGroup;
    DBRadioGroup26: TDBRadioGroup;
    DBRadioGroup27: TDBRadioGroup;
    DBRadioGroup28: TDBRadioGroup;
    DBRadioGroup29: TDBRadioGroup;
    DBRadioGroup30: TDBRadioGroup;
    DBRadioGroup31: TDBRadioGroup;
    DBRadioGroup32: TDBRadioGroup;
    DBRadioGroup33: TDBRadioGroup;
    DBRadioGroup34: TDBRadioGroup;
    DBRadioGroup35: TDBRadioGroup;
    DBRadioGroup36: TDBRadioGroup;
    DBRadioGroup37: TDBRadioGroup;
    DBRadioGroup38: TDBRadioGroup;
    DBRadioGroup39: TDBRadioGroup;
    DBRadioGroup40: TDBRadioGroup;
    TabSheet1: TTabSheet;
    DBMemo4: TDBMemo;
    DBMemo5: TDBMemo;
    procedure btnGravarClick(Sender: TObject);
    procedure btnIncluirClick(Sender: TObject);
    procedure FormShow(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fFichaMedica: TfFichaMedica;

implementation

uses UDm;

{$R *.dfm}

procedure TfFichaMedica.btnGravarClick(Sender: TObject);
begin
    if (cdsFicha.State in [dsInsert]) then
    begin
     if dm.c_6_genid.Active then
        dm.c_6_genid.Close;
      dm.c_6_genid.CommandText := 'SELECT CAST(GEN_ID(GEN_FICHAMEDICA, 1) as INTEGER) AS CODIGO FROM RDB$DATABASE';
      dm.c_6_genid.Open;
      cdsFichaID_FICHA.AsInteger := dm.c_6_genidCODIGO.AsInteger;
      cdsFichaRA.AsString := dm.cds_alunoRA.AsString ;
      dm.c_6_genid.Close;
    end;
  inherited;

end;

procedure TfFichaMedica.btnIncluirClick(Sender: TObject);
begin
  inherited;
  DBComboBox5.SetFocus;
end;

procedure TfFichaMedica.FormShow(Sender: TObject);
begin
  inherited;
  if (cdsFicha.Active) then
    cdsFicha.Close;
  cdsFicha.Params[0].AsString := dm.cds_alunoRA.AsString;
  cdsFicha.Open;  
end;

end.
